apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: todo-app
    template:
        metadata:
            labels:
                app: todo-app
        spec:
            containers:
                - name: todo-app
                  image: your-registry/todo-app:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: DATABASE_URL
                        value: "postgres://todo_user:secure_password@postgres:5432/todo_db"

