apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app
    namespace: gitops-todo
spec:
    template:
        spec:
            containers:
                -   name: todo-app
                    image: dhinojosa/gitops-todo:2024.12.02.194403
                    env:
                        - name: DB_PASSWORD
                          valueFrom:
                              secretKeyRef:
                                  name: postgres-staging-postgresql
                                  key: postgres-password

