apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app
    namespace: gitops-todo
spec:
    template:
        spec:
            containers:
                -   name: todo-app
                    image: SliderCO-007/gitops-todo:2025.07.18.190805
                    env:
                        -   name: DB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: my-postgres-postgresql
                                    key: password
    replicas: 5
