apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
        - name: POSTGRES_DB
          value: "todo_db_staging"
        - name: POSTGRES_PASSWORD
          value: "staging_password"
