namespace: gitops-todo
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patch-deployment.yaml
- path: patch-ingress.yaml
configMapGenerator:
- behavior: merge
  literals:
  - POSTGRES_HOST="tododb-postgresql.default.svc.cluster.local"
  - POSTGRES_DB="todo_db"
  - POSTGRES_USER="admin"
  name: postgres-config
