namespace: gitops-todo
resources:
- ../../base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patch-deployment.yaml
- path: patch-ingress.yaml
configMapGenerator:
- behavior: merge
  literals:
  - POSTGRES_HOST="prod-postgres.c6xa6z6daoyd.us-west-2.rds.amazonaws.com"
  - POSTGRES_DB="todo_db"
  - POSTGRES_USER="postgres"
  name: postgres-config
