apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  template:
    spec:
      containers:
      - name: todo-app
        env:
        - name: DATABASE_URL
          value: "postgres://todo_user:production_password@todo-db.production.svc.cluster.local:5432/todo_db_production"
