resources:
    - deployment.yaml
    - service.yaml
    - ingress.yaml
configMapGenerator:
    - name: postgres-config
      literals:
          - POSTGRES_DB="todo_db"
          - POSTGRES_USER="todo_user"
